import 'package:firebase_database/firebase_database.dart';

class Message{

  String key;
  String text;
  String type;

  Message(this.text,this.type);
  //Both text message and type is to be provided when object is created. the id will be generated by real time database

  Message.fromSnapShot(DataSnapshot snapshot):
      key = snapshot.key,
      text = snapshot.value["message"],
      type = snapshot.value['type'];


  toJson(){
    return {
      "type" : type,
      "message" : text
    };
  }
}

/*
When data is fetched from Firebase RTDB, it is in json format. Hence we have the Message.fromSnapshot(DataSnapshot snapshot)
 allows us to map data from json format to Message format. The toJson() does the opposite which is to map the
 data back into json format before we upload into Firebase RTDB.
 */